# server port
# web.xml

server:
  port: 9090
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
# session(1800 seconds = 30 minutes)
    session:
      timeout: 1800


spring:
# servlet-context
  web:
    resources:
      static-locations: /resources/**
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
     
# database connection
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://localhost:3306/sporters?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      jdbc-url: jdbc:mysql://203.245.44.105:3306/sporters?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: sporters
      password: sporters!!

# email
  mail:
    host: smtp.gmail.com
    port: 587
    username: nayoung181818@gmail.com
    password: daqumhodkgctfiee
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#  main:
#    web-application-type: none
      
# mybatis
mybatis:
  config-location: mybatis/config/mybatis-config.xml
  mapper-locations: mybatis/mapper/*.xml
