# server port
# web.xml

server:
  port: 9090
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
# session(1800 seconds = 30 minutes)
    session:
      timeout: 1800


spring:
# servlet-context
  web:
    resources:
      static-locations: /resources/**
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
     
# database connection
  datasource:
    hikari:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@localhost:1521:xe
      username: SCOTT
      password: TIGER
      
# mybatis
mybatis:
  config-location: mybatis/config/mybatis-config.xml
  mapper-locations: mybatis/mapper/*.xml
