DROP TABLE ATTACH;
DROP TABLE IMAGE;

DROP TABLE SINGO;
DROP TABLE FREE_COMMENT;
DROP TABLE FREE;
DROP TABLE SPO_COMMENT;
DROP TABLE SPO_REVIEW;
DROP TABLE JOIN_USERS;
DROP TABLE LOCALS_COMMENT;
DROP TABLE LOCALS;
DROP TABLE LOCALS_CATEGORY;













/** 지역게시판 시작 */
CREATE TABLE LOCALS_CATEGORY(
    LOCAL_NO NUMBER NOT NULL,
    LOCAL VARCHAR2(30 BYTE) NOT NULL,
    PRIMARY KEY(LOCAL_NO)
);


CREATE TABLE LOCALS(
    LOCAL_BOARD_NO NUMBER NOT NULL,
    TITLE VARCHAR2(100 BYTE) NOT NULL,
    CONTENT CLOB NOT NULL,
    CREATE_DATE DATE NOT NULL,
    HIT NUMBER NOT NULL,
    USER_NO NUMBER NOT NULL,
    STATE NUMBER(1) NOT NULL,
    COMMENT_ID VARCHAR2(30 BYTE) NOT NULL,
    MAX_USER NUMBER NULL,
    LOCAL_NO NUMBER NOT NULL,
    IP VARCHAR2(30 BYTE) NULL,
    MODIFY_DATE  DATE NULL,
    PRIMARY KEY(LOCAL_BOARD_NO),
    FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO) ON DELETE SET NULL,
    FOREIGN KEY (LOCAL_NO) REFERENCES LOCAL_CATEGORY(LOCAL_NO) ON DELETE SET NULL    
    );

CREATE TABLE LOCALS_COMMENT(
    LOCAL_CO_NO NUMBER NOT NULL,
    LOCAL_BOARD_NO NUMBER NOT NULL,
    COMM_CONTENT VARCHAR2(1000 BYTE) NOT NULL,
    COMM_CREATE_DATE DATE NOT NULL,
    STATE NUMBER(1) NOT NULL,
    DEPTH NUMBER(2) NOT NULL,
    GROUP_NO NUMBER NOT NULL,
    GROUP_ORDER NUMBER NOT NULL,
    USER_NO NUMBER NOT NULL,
    PRIMARY KEY (LOCAL_CO_NO),
    FOREIGN KEY(LOCAL_BOARD_NO) REFERENCES LOCALS (LOCAL_BOARD_NO) ON DELETE CASCADE,  
    FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO) ON DELETE SET NULL
);
    /* 지역게시판 참여자 리스트 */
CREATE TABLE JOIN_USERS(
    USER_NO NUMBER NOT NULL,
    LOCAL_BOARD_NO NUMBER NOT NULL,    
    FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO) ON DELETE CASCADE,
    FOREIGN KEY (LOCAL_BOARD_NO) REFERENCES LOCALS(LOCAL_BOARD_NO) ON DELETE CASCADE
);

/** 지역게시판 끝 */

/** 운동후기 게시판 시작 */
CREATE TABLE SPO_REVIEW(
    SPO_REVIEW_NO NUMBER NOT NULL,
    TITLE VARCHAR2(100 BYTE) NOT NULL,
    CONTENT CLOB NOT NULL,
    CREATE_DATE DATE NOT NULL,
    HIT NUMBER NOT NULL,
    USER_NO NUMBER NOT NULL,
    STATE NUMBER(1) NULL,
    LOCAL_BOARD_NO NUMBER NOT NULL,
    IP VARCHAR2(30 BYTE) NOT NULL,
    MODIFY_DATE DATE NULL,
    
    PRIMARY KEY (SPO_REVIEW_NO),
    FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO) ON DELETE SET NULL,
    FOREIGN KEY (LOCAL_BOARD_NO) REFERENCES LOCALS(LOCAL_BOARD_NO) ON DELETE SET NULL    
);


CREATE TABLE SPO_COMMENT(
    SPO_CO_NO NUMBER NOT NULL,
    SPO_REVIEW_NO NUMBER NOT NULL,
    COMM_CONTENT VARCHAR2(1000 BYTE)NOT NULL,
    COMM_CREATE_DATE DATE NOT NULL,
    STATE NUMBER(1) NOT NULL,
    DEPTH NUMBER(2) NOT NULL,
    GROUP_NO NUMBER NOT NULL,
    GROUP_ORDER NUMBER NOT NULL,
    USER_NO NUMBER NOT NULL,
    PRIMARY KEY (SPO_CO_NO),
    FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO) ON DELETE SET NULL,
    FOREIGN KEY (SPO_REVIEW_NO) REFERENCES SPO_REVIEW (SPO_REVIEW_NO) ON DELETE SET NULL    
    );
/** 운동후기 게시판 끝 */

/** 자유게시판 시작  */
CREATE TABLE FREE(
    FREE_NO NUMBER NOT NULL,
    CONTENT CLOB NOT NULL,
    CREATE_DATE DATE NOT NULL,
    HIT NUMBER NOT NULL,
    USER_NO NUMBER NOT NULL,
    STATE NUMBER(1) NOT NULL,
    IP VARCHAR2(30 BYTE) NULL,
    MODIFY_DATE DATE NULL,
    PRIMARY KEY (FREE_NO),
    FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO) ON DELETE SET NULL
);

CREATE TABLE FREE_COMMENT(
    FREE_CO_NO NUMBER NOT NULL,
    FREE_NO NUMBER NOT NULL,
    COMM_CONTENT VARCHAR2(1000 BYTE)NOT NULL,
    COMM_CREATE_DATE DATE NOT NULL,
    STATE NUMBER(1) NOT NULL,
    DEPTH NUMBER(2) NOT NULL,
    GROUP_NO NUMBER NOT NULL,
    GROUP_ORDER NUMBER NOT NULL,
    USER_NO NUMBER NOT NULL,
    PRIMARY KEY (FREE_CO_NO),
    FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO) ON DELETE SET NULL,
    FOREIGN KEY (FREE_NO) REFERENCES FREE (FREE_NO) ON DELETE CASCADE
);
/** 자유게시판 끝  */

/** 신고게시판 시작 */
CREATE TABLE SINGO(
   SINGO_NO NUMBER NOT NULL,
   SINGO_TITLE VARCHAR2(1000 BYTE) NOT NULL,
   SINGO_CONTENT VARCHAR2(4000 BYTE) NOT NULL,
   SINGO_CREATE_DATE DATE NOT NULL,
   SINGO_HIT NUMBER NOT NULL,
   USER_NO NUMBER NOT NULL,
   FREE_NO NUMBER NOT NULL,
   PRIMARY KEY (SINGO_NO),
   FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO) ON DELETE SET NULL,
   FOREIGN KEY (FREE_NO) REFERENCES FREE (FREE_NO) ON DELETE SET NULL
);
/** 신고게시판 끝 */

/** 첨부게시판 시작 */
CREATE TABLE IMAGE(
    IMAGE_NO NUMBER NOT NULL,
    LOCAL_BOARD_NO NUMBER NOT NULL,
    SPO_REVIEW_NO NUMBER NOT NULL,
    FREE_NO NUMBER NOT NULL,
    FILESYSTEM VARCHAR2(40 BYTE) NULL,
    PRIMARY KEY (IMAGE_NO),
    FOREIGN KEY (LOCAL_BOARD_NO) REFERENCES LOCALS(LOCAL_BOARD_NO) ON DELETE CASCADE,
    FOREIGN KEY (SPO_REVIEW_NO) REFERENCES SPO_REVIEW(SPO_REVIEW_NO) ON DELETE CASCADE,
    FOREIGN KEY (FREE_NO) REFERENCES FREE(FREE_NO) ON DELETE CASCADE
);


CREATE TABLE ATTACH(
    ATTACH_NO NUMBER NOT NULL,
    LOCAL_BOARD_NO NUMBER NOT NULL,
    SPO_REVIEW_NO NUMBER NOT NULL,
    FREE_NO NUMBER NOT NULL,
    PATH VARCHAR2(300 BYTE) NOT NULL,
    ORIGIN VARCHAR2(300 BYTE) NULL,
    FILESYSTEM VARCHAR2(40 BYTE) NULL,
    DOWNLOAD_CNT NUMBER NULL,
    PRIMARY KEY (ATTACH_NO),
    FOREIGN KEY (LOCAL_BOARD_NO) REFERENCES LOCALS(LOCAL_BOARD_NO) ON DELETE CASCADE,
    FOREIGN KEY (SPO_REVIEW_NO) REFERENCES SPO_REVIEW(SPO_REVIEW_NO) ON DELETE CASCADE,
    FOREIGN KEY (FREE_NO) REFERENCES FREE(FREE_NO) ON DELETE CASCADE
);


/** 첨부게시판 끝 */

