DROP SEQUENCE USERS_SEQ;
DROP SEQUENCE ORDERS_SEQ;
DROP SEQUENCE CART_SEQ;
DROP SEQUENCE PROD_CATEGORY_SEQ;
DROP SEQUENCE PRODUCT_SEQ;
DROP SEQUENCE PICK_SEQ;
DROP SEQUENCE SHOP_REVIEW_SEQ;
DROP SEQUENCE CART_LIST_SEQ;
DROP SEQUENCE PROD_DETAIL_IMAGE_SEQ;

CREATE SEQUENCE USERS_SEQ;
CREATE SEQUENCE ORDERS_SEQ;
CREATE SEQUENCE CART_SEQ;
CREATE SEQUENCE PROD_CATEGORY_SEQ;
CREATE SEQUENCE PRODUCT_SEQ;
CREATE SEQUENCE PICK_SEQ;
CREATE SEQUENCE SHOP_REVIEW_SEQ;
CREATE SEQUENCE CART_LIST_SEQ;
CREATE SEQUENCE PROD_DETAIL_IMAGE_SEQ;

DROP TABLE PROD_DETAIL_IMAGE;
DROP TABLE CART_LIST;
DROP TABLE SHOP_REVIEW;
DROP TABLE PICK;
DROP TABLE PRODUCT;
DROP TABLE PROD_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE CART;
DROP TABLE ORDERS;
DROP TABLE USERS;

CREATE TABLE USERS (
	USER_NO	NUMBER	NOT NULL,
	ID	VARCHAR2(30 BYTE)	NOT NULL,
	NICKNAME	VARCHAR2(24 BYTE)	NOT NULL,
	PW	VARCHAR2(64 BYTE)	NOT NULL,
	NAME	VARCHAR2(20 BYTE)	NOT NULL,
	GENDER	VARCHAR2(2 BYTE)	NOT NULL,
	EMAIL	VARCHAR2(50 BYTE)	NOT NULL,
	MOBILE	VARCHAR2(11 BYTE)	NOT NULL,
	BIRTHYEAR	VARCHAR2(4 BYTE)	NOT NULL,
	BIRTHMONTH	VARCHAR2(2 BYTE)	NOT NULL,
	BIRTHDAY	VARCHAR2(2 BYTE)	NOT NULL,
	POSTCODE	VARCHAR2(5 BYTE)	NULL,
	ROAD_ADDRESS	VARCHAR2(100 BYTE)	NULL,
	JIBUN_ADDRESS	VARCHAR2(100 BYTE)	NULL,
	DETAIL_ADDRESS	VARCHAR2(100 BYTE)	NULL,
	AGREE_CODE	NUMBER	NOT NULL,
	SNS_TYPE	VARCHAR2(10 BYTE)	NULL,
	JOIN_DATE	DATE	NOT NULL,
	INFO_MODIFY_DATE	DATE	NULL,
    PW_MODIFY_DATE  DATE    NULL,
	SESSION_ID	VARCHAR2(32 BYTE)	NULL,
	SESSION_LIMIT_DATE	DATE	NULL,
    BANNED_STATE    NUMBER(1)   NOT NULL,
    PRIMARY KEY(USER_NO)
);

CREATE TABLE ORDERS (
	ORDER_NO	NUMBER	NOT NULL,
	USER_NO	NUMBER	NOT NULL,
    CART_NO NUMBER  NOT NULL,
	PAYMENT	NUMBER	NULL,
	NAME	VARCHAR2(100 BYTE)	NOT NULL,
    MOBILE  VARCHAR2(11 BYTE)   NOT NULL,
    POSTCODE VARCHAR2(5 BYTE),
    LOAD_ADDRESS VARCHAR2(100 BYTE),
    JIBUN_ADDRESS VARCHAR2(100 BYTE),
    DETAIL_ADDRESS VARCHAR2(100 BYTE),
	ORDER_DATE	DATE	NOT NULL,
    PRIMARY KEY(ORDER_NO),
    FOREIGN KEY(USER_NO) REFERENCES USERS(USER_NO)
);

CREATE TABLE CART (
	CART_NO	NUMBER	NOT NULL,
    USER_NO NUMBER  NOT NULL,
    PRIMARY KEY(CART_NO),
    FOREIGN KEY(USER_NO) REFERENCES USERS(USER_NO)
);

CREATE TABLE PROD_CATEGORY (
    PROD_CATEGORY_NO    NUMBER  NOT NULL,
    PROD_CATEGORY_NAME  VARCHAR2(30 BYTE)   NOT NULL,
    PRIMARY KEY(PROD_CATEGORY_NO)
);

CREATE TABLE PRODUCT (
	PROD_NO	NUMBER	NOT NULL,
    PROD_CATEGORY_NO NUMBER NOT NULL,
	PROD_NAME	VARCHAR2(100 BYTE)	NOT NULL,
	PRICE	NUMBER(10)	DEFAULT 0	NOT NULL,
	DISCOUNT	NUMBER(10)	NULL,
	PROD_CONTENT	CLOB	NULL,
	ORIGIN	VARCHAR2(100 BYTE)	NULL,
	IS_SOLDOUT	NUMBER	DEFAULT 0	NULL,
    STOCK   NUMBER,
    FILESYSTEM  VARCHAR2(42 BYTE),
    PROD_THUMBNAIL  NUMBER,
    PRIMARY KEY(PROD_NO),
    FOREIGN KEY(PROD_CATEGORY_NO) REFERENCES PROD_CATEGORY(PROD_CATEGORY_NO)
);

CREATE TABLE PICK (
	USER_NO	NUMBER	NOT NULL,
	PROD_NO	NUMBER	NOT NULL,
    FOREIGN KEY(USER_NO) REFERENCES USERS(USER_NO),
    FOREIGN KEY(PROD_NO) REFERENCES PRODUCT(PROD_NO)
);

CREATE TABLE SHOP_REVIEW (
	REVIEW_NO	NUMBER	NOT NULL,
	ORDER_NO	NUMBER	NOT NULL,
	STAR	NUMBER(2,1)	NOT NULL,
	CONTENT	VARCHAR2(4000 BYTE)	NULL,
	REVIEW_DATE	DATE	NULL,
    PRIMARY KEY(REVIEW_NO),
    FOREIGN KEY(ORDER_NO) REFERENCES ORDERS(ORDER_NO)
);

CREATE TABLE CART_LIST (
	CART_NO	NUMBER	NOT NULL,
	PROD_NO	NUMBER	NOT NULL,
	PROD_CNT	NUMBER	NOT NULL,
	FOREIGN KEY(CART_NO) REFERENCES CART(CART_NO),
    FOREIGN KEY(PROD_NO) REFERENCES PRODUCT(PROD_NO)
);

CREATE TABLE PROD_DETAIL_IMAGE (
    PROD_DETAIL_IMAGE_NO NUMBER NOT NULL,
    PROD_NO NUMBER  NOT NULL,
    FILESYSTEM  VARCHAR2(40 BYTE),
    PRIMARY KEY(PROD_DETAIL_IMAGE_NO),
    FOREIGN KEY(PROD_NO) REFERENCES PRODUCT(PROD_NO)
);