DROP TABLE IF EXISTS PROD_THUMBNAIL;
DROP TABLE IF EXISTS PROD_DETAIL_IMAGE;
DROP TABLE IF EXISTS CART_LIST;
DROP TABLE IF EXISTS SHOP_REVIEW;
DROP TABLE IF EXISTS PICK;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS PROD_CATEGORY;
DROP TABLE IF EXISTS CART;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
   USER_NO      INT   NOT NULL AUTO_INCREMENT,
   ID      VARCHAR(30)   NOT NULL,
   NICKNAME   VARCHAR(24)   NOT NULL,
   PW      VARCHAR(64)   NOT NULL,
   NAME      VARCHAR(20)   NOT NULL,
   GENDER      VARCHAR(2)   NOT NULL,
   EMAIL      VARCHAR(50)   NOT NULL,
   MOBILE      VARCHAR(11)   NOT NULL,
   BIRTHYEAR   VARCHAR(4)   NOT NULL,
   BIRTHMONTH   VARCHAR(2)   NOT NULL,
   BIRTHDAY   VARCHAR(2)   NOT NULL,
   POSTCODE   VARCHAR(5)   NULL,
   ROAD_ADDRESS   VARCHAR(100)   NULL,
   JIBUN_ADDRESS   VARCHAR(100)   NULL,
   DETAIL_ADDRESS   VARCHAR(100)   NULL,
   AGREE_CODE   INT   NOT NULL,
   SNS_TYPE   VARCHAR(10)   NULL,
   JOIN_DATE      DATE   NOT NULL,
   INFO_MODIFY_DATE   DATE   NULL,
   PW_MODIFY_DATE       DATE NULL,
   SESSION_ID   VARCHAR(32)   NULL,
   SESSION_LIMIT_DATE   DATE   NULL,
    BANNED_STATE    INT NOT NULL,
	PRIMARY KEY(USER_NO)
);

CREATE TABLE SLEEP_USERS (
   USER_NO         INT      NOT NULL,
   SLEEP_USER_ID   VARCHAR(30)      NOT NULL,
   SLEEP_USER_PW   VARCHAR( 64)      NOT NULL,
   SLEEP_USER_NICKNAME   VARCHAR(24)      NOT NULL,
   SLEEP_USER_NAME      VARCHAR(20)      NOT NULL,
   SLEEP_USER_GENDER   VARCHAR(2)      NOT NULL,
   SLEEP_USER_EMAIL      VARCHAR(50)      NOT NULL,
   SLEEP_USER_MOBILE      VARCHAR(11)      NOT NULL,
   SLEEP_USER_BIRTHYEAR   VARCHAR(4)      NOT NULL,
   SLEEP_USER_BIRTHMONTH   VARCHAR(4)      NOT NULL,
   SLEEP_USER_BIRTHDAY   VARCHAR(4)      NOT NULL,
   POSTCODE      VARCHAR(5)      NULL,
   ROAD_ADDRESS   VARCHAR(100)      NULL,
   JIBUN_ADDRESS   VARCHAR(100)      NULL,
   DETAIL_ADDRESS   VARCHAR(100)      NULL,
   AGREE_CODE      INT      NOT NULL,
   SNS_TYPE      VARCHAR(10)      NULL,
   JOIN_DATE      DATE      NOT NULL,
   LAST_LOGIN_DATE   DATE      NULL,
   SLEEP_DATE      DATE      NULL,
PRIMARY KEY(USER_NO)
);

CREATE TABLE ORDERS (
    ORDER_NO INT NOT NULL AUTO_INCREMENT,
    USER_NO	INT	NOT NULL,
    CART_NO INT  NOT NULL,
    PAYMENT	INT	NULL,
    NAME	VARCHAR(100) NOT NULL,
    MOBILE  VARCHAR(11)  NOT NULL,
    POSTCODE VARCHAR(5),
    LOAD_ADDRESS VARCHAR(100),
    JIBUN_ADDRESS VARCHAR(100),
    DETAIL_ADDRESS VARCHAR(100),
    ORDER_DATE	DATE NOT NULL,
    PRIMARY KEY(ORDER_NO),
    FOREIGN KEY(USER_NO) REFERENCES USERS(USER_NO) ON DELETE CASCADE
);

CREATE TABLE CART (
    CART_NO	INT	NOT NULL AUTO_INCREMENT,
    USER_NO INT  NOT NULL,
    PRIMARY KEY(CART_NO),
    FOREIGN KEY(USER_NO) REFERENCES USERS(USER_NO) ON DELETE CASCADE
);

CREATE TABLE PROD_CATEGORY (
    PROD_CATEGORY_NO INT  NOT NULL AUTO_INCREMENT,
    PROD_CATEGORY_NAME  VARCHAR(30)   NOT NULL,
    PRIMARY KEY(PROD_CATEGORY_NO)
);

CREATE TABLE PRODUCT (
    PROD_NO INT	NOT NULL AUTO_INCREMENT,
    PROD_CATEGORY_NO INT,
    PROD_NAME	VARCHAR(100)	NOT NULL,
    PRICE		INT	NOT NULL,
    DISCOUNT	INT	NULL,
    PROD_CONTENT	VARCHAR(20000)	NULL,
    ORIGIN	VARCHAR(100),
    STOCK   INT,
    PROD_CREATE_DATE DATE,
    PRIMARY KEY(PROD_NO),
    FOREIGN KEY(PROD_CATEGORY_NO) REFERENCES PROD_CATEGORY(PROD_CATEGORY_NO) ON DELETE SET NULL
);

CREATE TABLE PICK (
    USER_NO	INT,
    PROD_NO	INT,
    FOREIGN KEY(USER_NO) REFERENCES USERS(USER_NO),
    FOREIGN KEY(PROD_NO) REFERENCES PRODUCT(PROD_NO) ON DELETE SET NULL
);

CREATE TABLE SHOP_REVIEW (
    REVIEW_NO	INT	NOT NULL,
    ORDER_NO	INT,
    STAR		DECIMAL(2,1)	NOT NULL,
    CONTENT	VARCHAR(20000)	NULL,
    REVIEW_DATE	DATE	NULL,
    PRIMARY KEY(REVIEW_NO),
    FOREIGN KEY(ORDER_NO) REFERENCES ORDERS(ORDER_NO) ON DELETE SET NULL
);

CREATE TABLE CART_LIST (
    CART_NO	INT	NOT NULL,
    PROD_NO	INT,
    PROD_CNT INT NOT NULL,
    FOREIGN KEY(CART_NO) REFERENCES CART(CART_NO),
    FOREIGN KEY(PROD_NO) REFERENCES PRODUCT(PROD_NO) ON DELETE CASCADE
);

CREATE TABLE PROD_DETAIL_IMAGE (
    PROD_DETAIL_IMAGE_NO INT NOT NULL,
    PROD_NO INT,
    FILESYSTEM  VARCHAR(40),
    PRIMARY KEY(PROD_DETAIL_IMAGE_NO),
    FOREIGN KEY(PROD_NO) REFERENCES PRODUCT(PROD_NO) ON DELETE CASCADE
);

CREATE TABLE PROD_THUMBNAIL(
    TN_NO INT NOT NULL AUTO_INCREMENT,
    PROD_NO INT,
    TN_PATH VARCHAR(300),
    TN_ORIGIN VARCHAR(300),
    TN_FILESYSTEM VARCHAR(42),
    IS_THUMBNAIL INT,
    PRIMARY KEY(TN_NO),
    FOREIGN KEY(PROD_NO) REFERENCES PRODUCT(PROD_NO) ON DELETE CASCADE
);

INSERT INTO PROD_CATEGORY (PROD_CATEGORY_NAME)
    VALUES ('음식');
INSERT INTO PROD_CATEGORY (PROD_CATEGORY_NAME)
    VALUES ('의류');
INSERT INTO PROD_CATEGORY (PROD_CATEGORY_NAME)
    VALUES ('물건');
COMMIT;
