DROP TABLE SINGO;
CREATE TABLE "SINGO" (
	"SINGO_NO"	NUMBER		NOT NULL,
	"SINGO_TITLE"	VARCHAR2(100 BYTE)		NOT NULL,
	"SINGO_CONTENT"	VARCHAR2(4000 BYTE)		NOT NULL,
	"SINGO_CREATE_DATE"	DATE		NOT NULL,
	"SINGO_HIT"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"FREE_NO"	NUMBER		NOT NULL,
	PRIMARY KEY(SINGO_NO),
	FOREIGN KEY(USER_NO) REFERENCES USERS(USER_NO) ON DELETE SET NULL,
	FOREIGN KEY(FREE_NO) REFERENCES FREE(FREE_NO) ON DELETE CASCADE
);
